// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _20220614_TEST.Models;

#nullable disable

namespace _20220614_TEST.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220614070130_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_20220614_TEST.Models.tblActiveItem", b =>
                {
                    b.Property<int>("cItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cItemID"), 1L, 1);

                    b.Property<string>("cActiveDt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cItemID");

                    b.ToTable("tblActiveItem");
                });

            modelBuilder.Entity("_20220614_TEST.Models.tblSignup", b =>
                {
                    b.Property<string>("cMobile")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("cCreateDT")
                        .HasColumnType("datetime2");

                    b.Property<string>("cEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("cMobile");

                    b.ToTable("tblSignup");
                });

            modelBuilder.Entity("_20220614_TEST.Models.tblSignupItem", b =>
                {
                    b.Property<int>("cItemID")
                        .HasColumnType("int");

                    b.Property<string>("cMobile")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cItemID", "cMobile");

                    b.ToTable("tblSignupItem");
                });
#pragma warning restore 612, 618
        }
    }
}
